import { useEffect, useMemo, useState } from "react";
import { Link, useOutletContext, useParams } from "react-router-dom";
import { ArrowLeft, RefreshCw } from "lucide-react";
import {
  completeInspectionCase, createInspectionReinspection, getInspectionCase,
  prepareInspectionPackage, processInspectionConclusion, refreshInspectionWorkOrders,
  registerInspectionReport, sendInspectionPackage, updateInspectionCase,
  updateInspectionAssignment, updateInspectionChecklistItem,
  getInspectionCaseEvents,
} from "../../api/emberApi.js";

const STATUSES=["ATTENTION_REQUIRED","OFFER_REQUIRED","ORDERED","PLANNING_REQUIRED","PLANNED_UNCONFIRMED","PLANNED_CONFIRMED","EXECUTED_AWAITING_REPORT","REPORT_RECEIVED","REPAIR_REQUIRED","REINSPECTION_REQUIRED","CERTIFICATE_RECEIVED","CANCELLED"];
function formatDate(value){if(!value)return "-";const d=new Date(value);return Number.isNaN(d.getTime())?String(value):new Intl.DateTimeFormat("nl-NL",{dateStyle:"medium"}).format(d)}
function cleanDate(value){return value?String(value).slice(0,10):""}

export default function InspectionCasePage(){
  const {caseId}=useParams();const[data,setData]=useState(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  const {permissions=[]}=useOutletContext()||{};const[auditEvents,setAuditEvents]=useState([]);
  const can=(permission)=>permissions.includes(permission);
  const[editor,setEditor]=useState({});const[selectedPackageDocs,setSelectedPackageDocs]=useState([]);const[report,setReport]=useState({document_id:"",conclusion:"PENDING",inspection_date:"",inspection_body:"",report_reference:""});const[certificateId,setCertificateId]=useState("");
  async function load(){setLoading(true);setError("");try{const next=await getInspectionCase(caseId);setData(next);setEditor({status:next.case.status,due_date:cleanDate(next.case.due_date),inspection_body:next.case.inspection_body||"",assigned_user_id:next.case.assigned_user_id||"",assigned_role_code:next.case.assigned_role_code||"",logbook_linked:Boolean(next.case.logbook_linked),inspection_body_has_logbook_access:Boolean(next.case.inspection_body_has_logbook_access),document_package_available_in_logbook:Boolean(next.case.document_package_available_in_logbook),report_uploaded_to_logbook:Boolean(next.case.report_uploaded_to_logbook)});if(permissions.includes("inspection.audit.view")){const audit=await getInspectionCaseEvents(caseId);setAuditEvents(audit?.items||[])}}catch(e){setError(e?.message||"Inspectie laden is mislukt.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[caseId,permissions.join("|")]);
  const chosenReportDocument=useMemo(()=>data?.document_choices?.find((doc)=>doc.document_id===report.document_id)||null,[data,report.document_id]);
  async function run(action,fallback){setBusy(true);setError("");try{await action();await load()}catch(e){setError(e?.message||fallback)}finally{setBusy(false)}}
  async function refresh(){return run(()=>refreshInspectionWorkOrders(caseId),"Werkbonverversing is mislukt.")}
  async function saveCase(){const caseFields={status:editor.status,due_date:editor.due_date,inspection_body:editor.inspection_body,logbook_linked:editor.logbook_linked,inspection_body_has_logbook_access:editor.inspection_body_has_logbook_access,document_package_available_in_logbook:editor.document_package_available_in_logbook,report_uploaded_to_logbook:editor.report_uploaded_to_logbook};return run(()=>updateInspectionCase(caseId,{...caseFields,row_version:data.case.row_version}),"Inspectie bijwerken is mislukt.")}
  async function saveAssignment(){return run(()=>updateInspectionAssignment(caseId,{row_version:data.case.row_version,assigned_user_id:editor.assigned_user_id||null,assigned_role_code:editor.assigned_role_code||null}),"Toewijzing bijwerken is mislukt.")}
  async function setChecklist(item,status,documentId=item.installation_document_id){const doc=data.document_choices.find((candidate)=>candidate.document_id===documentId);return run(()=>updateInspectionChecklistItem(caseId,item.inspection_case_document_requirement_id,{...item,status,row_version:item.row_version,installation_document_id:doc?.document_id||null,stored_file_id:doc?.stored_file_id||null}),"Checklist bijwerken is mislukt.")}
  async function createChecklistAction(item){return run(()=>updateInspectionChecklistItem(caseId,item.inspection_case_document_requirement_id,{...item,row_version:item.row_version,create_action:true,action_title:`Aanleveren: ${item.requirement_key.replaceAll("_"," ")}`}),"Checklistactie aanmaken is mislukt.")}
  async function preparePackageNow(){return run(()=>prepareInspectionPackage(caseId,{installation_document_ids:selectedPackageDocs,inspection_body:data.case.inspection_body,recipient_snapshot:{inspection_body:data.case.inspection_body}}),"Documentpakket voorbereiden is mislukt.")}
  async function sendPackageNow(pkg){const reference=window.prompt("Externe verzendreferentie of e-mailonderwerp",pkg.external_reference||"");if(reference===null)return;return run(()=>sendInspectionPackage(caseId,pkg.inspection_case_document_package_id,{row_version:pkg.row_version,external_reference:reference}),"Documentpakket verzenden is mislukt.")}
  async function registerReportNow(){if(!chosenReportDocument){setError("Kies eerst het exacte rapportbestand.");return}return run(()=>registerInspectionReport(caseId,{installation_document_id:chosenReportDocument.document_id,stored_file_id:chosenReportDocument.stored_file_id,conclusion:report.conclusion,inspection_date:report.inspection_date||null,inspection_body:report.inspection_body||data.case.inspection_body,report_reference:report.report_reference||null}),"Inspectierapport registreren is mislukt.")}
  async function conclude(conclusion){return run(()=>processInspectionConclusion(caseId,{row_version:data.case.row_version,conclusion,installation_certificate_id:conclusion==="PASS"?certificateId||null:null,note:conclusion==="FAIL"?"Herstelpunten uit het actuele inspectierapport uitvoeren.":null}),"Inspectieconclusie verwerken is mislukt.")}
  async function reinspection(){return run(()=>createInspectionReinspection(caseId,{due_date:data.case.due_date,inspection_body:data.case.inspection_body,assigned_user_id:data.case.assigned_user_id,assigned_role_code:data.case.assigned_role_code}),"Herinspectie aanmaken is mislukt.")}
  async function complete(){return run(()=>completeInspectionCase(caseId,{row_version:data.case.row_version}),"Inspectie afronden is mislukt.")}
  if(loading)return <div className="card inspection-empty">Inspectie laden...</div>;if(!data)return <div className="ember-error-text">{error||"Inspectie niet gevonden."}</div>;
  const item=data.case;
  return <div className="inspection-page">
    <div className="inspection-back"><Link className="btn btn-secondary" to="/inspecties"><ArrowLeft size={16}/>Terug</Link></div>
    <section className="card inspection-case-hero"><div><div className="inspection-scope-list">{data.scopes.map((s)=><i key={s.scope}>{s.scope.replace("_","-")}</i>)}</div><h1>{item.installation_name||item.atrium_installation_code}</h1><p className="ember-page-subtitle">Installatie {item.atrium_installation_code}{item.object_name?` ; ${item.object_name}`:""}{item.relation_name?` ; ${item.relation_name}`:""}</p></div><div className="inspection-case-hero__status"><span className="ember-label ember-label--warning">{item.status_display_name||item.status}</span><strong>{formatDate(item.due_date)}</strong></div></section>
    {error?<div className="ember-error-text">{error}</div>:null}
    <section className="inspection-detail-grid">
      <article className="card inspection-section"><div className="inspection-section__head"><div><h2>Casebesturing</h2><p className="ember-page-subtitle">Status, termijn, keuringsinstantie en toewijzing.</p></div>{can("inspection.update")?<button className="btn" disabled={busy} onClick={()=>void saveCase()}>Case opslaan</button>:null}</div><div className="inspection-editor-grid"><label><span>Status</span><select disabled={!can("inspection.update")} value={editor.status} onChange={(e)=>setEditor((v)=>({...v,status:e.target.value}))}>{STATUSES.map((status)=><option key={status}>{status}</option>)}</select></label><label><span>Vervaldatum</span><input disabled={!can("inspection.update")} type="date" value={editor.due_date} onChange={(e)=>setEditor((v)=>({...v,due_date:e.target.value}))}/></label><label><span>Keuringsinstantie</span><input disabled={!can("inspection.update")} value={editor.inspection_body} onChange={(e)=>setEditor((v)=>({...v,inspection_body:e.target.value}))}/></label><label><span>Toegewezen rol</span><input disabled={!can("inspection.assign")} value={editor.assigned_role_code} onChange={(e)=>setEditor((v)=>({...v,assigned_role_code:e.target.value,assigned_user_id:""}))} placeholder="INSPECTION_COORDINATOR"/></label></div>{can("inspection.assign")?<div className="guidance-media-actions"><button className="btn btn-secondary btn-compact" disabled={busy} onClick={()=>void saveAssignment()}>Toewijzing opslaan</button></div>:null}<div className="inspection-logbook-grid">{[["logbook_linked","Digitaal logboek gekoppeld"],["inspection_body_has_logbook_access","Keuringsinstantie heeft toegang"],["document_package_available_in_logbook","Documentpakket staat in logboek"],["report_uploaded_to_logbook","Rapport staat in logboek"]].map(([key,label])=><label key={key}><input disabled={!can("inspection.update")} type="checkbox" checked={Boolean(editor[key])} onChange={(e)=>setEditor((v)=>({...v,[key]:e.target.checked}))}/><span>{label}</span></label>)}</div></article>
      <article className="card inspection-section"><div className="inspection-section__head"><div><h2>Werkbon en planning</h2><p className="ember-page-subtitle">Live verifieerbaar via de Atrium Reader.</p></div>{can("inspection.refresh_workorder")?<button className="btn btn-secondary" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={16}/>{busy?"Verversen...":"Live verversen"}</button>:null}</div><dl className="inspection-facts"><div><dt>Werkbon</dt><dd>{item.atrium_work_order_code||"Nog niet gekoppeld"}</dd></div><div><dt>Afspraak</dt><dd>{item.appointment_status.replaceAll("_"," ")}</dd></div><div><dt>Gepland</dt><dd>{formatDate(item.planned_date)}</dd></div><div><dt>Uitgevoerd</dt><dd>{formatDate(item.execution_date)}</dd></div><div><dt>Certificeringsplicht</dt><dd>{data.certification_requirements.length?data.certification_requirements.map((row)=>row.scope.replace("_","-")).join(", "):"Niet vastgelegd"}</dd></div><div><dt>Huidig certificaat</dt><dd>{data.current_certificates.find((row)=>row.record_status==="CURRENT")?.certificate_number||"Geen"}</dd></div></dl>{data.work_orders.map((row)=><div className="inspection-workorder" key={row.atrium_work_order_key}><strong>{row.atrium_work_order_code} ; {row.work_order_title}</strong><span>{row.raw_status} ; {row.mapped_status.replaceAll("_"," ")}</span><small>Live gecontroleerd {formatDate(row.last_verified_at)}</small></div>)}</article>
    </section>
    <section className="card inspection-section"><div className="inspection-section__head"><div><h2>Voorbereidingschecklist</h2><p className="ember-page-subtitle">Koppel de exacte documentversie en controleer de beschikbaarheid.</p></div></div><div className="inspection-checklist">{data.checklist.map((row)=><div className="inspection-checklist__row inspection-checklist__row--wide" key={row.inspection_case_document_requirement_id}><div><strong>{row.requirement_key.replaceAll("_"," ")}</strong><small>{row.document_title||row.file_name||row.responsibility_type}</small>{can("inspection.checklist.manage")&&!row.follow_up_action_id&&row.status==="MISSING"?<button className="btn btn-secondary btn-compact" disabled={busy} onClick={()=>void createChecklistAction(row)}>Actie aanmaken</button>:null}</div><select disabled={busy||!can("inspection.checklist.manage")} value={row.installation_document_id||""} onChange={(e)=>void setChecklist(row,e.target.value?"AVAILABLE":"MISSING",e.target.value)}><option value="">Geen document gekoppeld</option>{data.document_choices.filter((doc)=>doc.document_type_key===row.document_type_key||row.requirement_level==="OPTIONAL").map((doc)=><option key={doc.document_id} value={doc.document_id}>{doc.title||doc.file_name}</option>)}</select><select disabled={busy||!can("inspection.checklist.manage")} value={row.status} onChange={(e)=>void setChecklist(row,e.target.value)}><option>MISSING</option><option>AVAILABLE</option><option>CHECKED</option><option>SENT</option><option>WAIVED</option></select></div>)}</div></section>
    <section className="inspection-detail-grid">
      <article className="card inspection-section"><div className="inspection-section__head"><div><h2>Documentpakket</h2><p className="ember-page-subtitle">Iedere versie bewaart exacte StoredFile-verwijzingen.</p></div>{can("inspection.package.prepare")?<button className="btn" disabled={busy||!selectedPackageDocs.length} onClick={()=>void preparePackageNow()}>Pakket voorbereiden</button>:null}</div><div className="inspection-document-choice-list">{data.document_choices.map((doc)=><label key={doc.document_id}><input disabled={!can("inspection.package.prepare")} type="checkbox" checked={selectedPackageDocs.includes(doc.document_id)} onChange={(e)=>setSelectedPackageDocs((current)=>e.target.checked?[...current,doc.document_id]:current.filter((id)=>id!==doc.document_id))}/><span><strong>{doc.title||doc.file_name}</strong><small>{doc.document_type_key}</small></span></label>)}</div><div className="inspection-timeline">{data.packages.map((pkg)=><div key={pkg.inspection_case_document_package_id}><strong>Documentpakket v{pkg.package_version}</strong><span>{pkg.package_status} ; {pkg.items.length} bestanden</span>{can("inspection.package.send")&&pkg.package_status==="DRAFT"?<button className="btn btn-secondary btn-compact" disabled={busy} onClick={()=>void sendPackageNow(pkg)}>Verzending registreren</button>:null}</div>)}</div></article>
      <article className="card inspection-section"><h2>Inspectierapport</h2><div className="inspection-editor-grid"><label className="inspection-editor-grid__wide"><span>Exact rapportbestand</span><select disabled={!can("inspection.report.register")} value={report.document_id} onChange={(e)=>setReport((v)=>({...v,document_id:e.target.value}))}><option value="">Kies een document</option>{data.document_choices.map((doc)=><option key={doc.document_id} value={doc.document_id}>{doc.title||doc.file_name}</option>)}</select></label><label><span>Inspectiedatum</span><input disabled={!can("inspection.report.register")} type="date" value={report.inspection_date} onChange={(e)=>setReport((v)=>({...v,inspection_date:e.target.value}))}/></label><label><span>Voorlopige conclusie</span><select disabled={!can("inspection.report.register")} value={report.conclusion} onChange={(e)=>setReport((v)=>({...v,conclusion:e.target.value}))}><option>PENDING</option><option>PASS</option><option>FAIL</option></select></label><label><span>Keuringsinstantie</span><input disabled={!can("inspection.report.register")} value={report.inspection_body} onChange={(e)=>setReport((v)=>({...v,inspection_body:e.target.value}))}/></label><label><span>Rapportreferentie</span><input disabled={!can("inspection.report.register")} value={report.report_reference} onChange={(e)=>setReport((v)=>({...v,report_reference:e.target.value}))}/></label></div>{can("inspection.report.register")?<button className="btn" disabled={busy||!report.document_id} onClick={()=>void registerReportNow()}>Rapport registreren</button>:null}<div className="inspection-timeline">{data.reports.map((row)=><div key={row.inspection_case_report_id}><strong>{row.document_title||row.file_name}</strong><span>{row.conclusion} ; ontvangen {formatDate(row.received_at)}</span></div>)}</div></article>
    </section>
    <section className="inspection-detail-grid">
      <article className="card inspection-section"><h2>Conclusie en afronding</h2><label className="ui-stack-sm"><span>Gekoppeld inspectiecertificaat voor PASS</span><select disabled={!can("inspection.conclusion.process")} value={certificateId} onChange={(e)=>setCertificateId(e.target.value)}><option value="">Kies een certificaat</option>{data.certificate_choices.map((cert)=><option key={cert.installation_certificate_id} value={cert.installation_certificate_id}>{cert.certificate_number||cert.description}</option>)}</select></label><div className="guidance-media-actions">{can("inspection.conclusion.process")?<><button className="btn" disabled={busy||!certificateId} onClick={()=>void conclude("PASS")}>PASS verwerken</button><button className="btn btn-secondary" disabled={busy} onClick={()=>void conclude("FAIL")}>FAIL en herstelactie</button></>:null}{can("inspection.reinspection.create")?<button className="btn btn-secondary" disabled={busy||item.conclusion!=="FAIL"} onClick={()=>void reinspection()}>Herinspectie aanmaken</button>:null}{can("inspection.complete")?<button className="btn" disabled={busy} onClick={()=>void complete()}>Case afronden</button>:null}</div></article>
      <article className="card inspection-section"><h2>Open acties</h2><div className="inspection-timeline">{data.actions.map((action)=><div key={action.follow_up_action_id}><strong>{action.workflow_title}</strong><span>{action.status} ; {action.responsibility_type}</span>{(action.drawing_pins||[]).map((pin)=><Link className="btn btn-secondary btn-compact" key={pin.drawing_pin_id} to={`/installaties/${encodeURIComponent(item.atrium_installation_code)}?tab=drawings&drawing=${encodeURIComponent(pin.installation_document_id)}&page=${encodeURIComponent(pin.page_number)}&pin=${encodeURIComponent(pin.drawing_pin_id)}`}>Toon op tekening ; pagina {pin.page_number}</Link>)}</div>)}{!data.actions.length?<p className="ember-page-subtitle">Geen acties voor deze inspectiecase.</p>:null}</div></article>
    </section>
    {permissions.includes("inspection.audit.view")?<section className="card inspection-section"><h2>Auditlog</h2><div className="inspection-timeline">{auditEvents.map((event)=><div key={event.inspection_case_event_id}><strong>{event.event_type.replaceAll("_"," ")}</strong><span>{formatDate(event.event_at)} ; {event.event_by||"systeem"}</span></div>)}</div></section>:null}
  </div>
}
