import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { getInspectionCases, getInstallationCertification, getInstallationOperationalSummary } from "../../api/emberApi.js";

export default function InspectionCasesTab({code}){
  const[items,setItems]=useState([]);const[operational,setOperational]=useState(null);const[certification,setCertification]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  useEffect(()=>{let cancelled=false;setLoading(true);Promise.all([getInspectionCases({q:code,active:"false",take:100}),getInstallationOperationalSummary(code),getInstallationCertification(code)]).then(([cases,summary,certs])=>{if(cancelled)return;setItems((cases?.items||[]).filter((item)=>item.atrium_installation_code===code));setOperational(summary?.item||null);setCertification(certs||null)}).catch((e)=>{if(!cancelled)setError(e?.message||"Inspecties laden is mislukt.")}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[code]);
  const active=useMemo(()=>items.filter((item)=>!["COMPLETED","CANCELLED"].includes(item.status)),[items]);const historical=useMemo(()=>items.filter((item)=>["COMPLETED","CANCELLED"].includes(item.status)),[items]);const currentCertificates=(certification?.certificates||[]).filter((cert)=>cert.certificate_type==="INSPECTION"&&cert.record_status==="CURRENT");const nextAction=active.find((item)=>Number(item.open_action_count||0)>0)||active[0]||null;
  return <div className="inspection-page"><section className="inspection-kpis"><div className="card"><span>Actuele status</span><strong>{operational?.active_inspection_case_status?.replaceAll("_"," ")||"Geen actieve case"}</strong></div><div className="card"><span>Volgende signalering</span><strong>{operational?.inspection_due_date?String(operational.inspection_due_date).slice(0,10):"-"}</strong></div><div className="card"><span>Inspectiecertificaat</span><strong>{currentCertificates[0]?.certificate_number||operational?.certificate_status||"Onbekend"}</strong></div><div className="card"><span>Eerstvolgende handeling</span><strong>{nextAction?.status?.replaceAll("_"," ")||"Geen"}</strong></div></section><section className="card inspection-section"><div className="inspection-section__head"><div><h2>Inspectiecases</h2><p className="ember-page-subtitle">Actuele en historische inspecties voor deze installatie.</p></div><Link className="btn btn-secondary" to="/inspecties">Alle inspecties</Link></div>{error?<div className="ember-error-text">{error}</div>:null}{loading?<div className="inspection-empty">Laden...</div>:items.length?<><h3>Actief</h3><div className="inspection-timeline">{active.map((item)=><Link key={item.inspection_case_id} to={`/inspecties/${item.inspection_case_id}`}><strong>{item.status_display_name||item.status}</strong><span>{item.inspection_type} ; {(item.scopes||[]).join(", ")} ; {item.due_date||"geen vervaldatum"}</span></Link>)}{!active.length?<p className="ember-page-subtitle">Geen actieve inspectiecases.</p>:null}</div><h3>Historie</h3><div className="inspection-timeline">{historical.map((item)=><Link key={item.inspection_case_id} to={`/inspecties/${item.inspection_case_id}`}><strong>{item.status_display_name||item.status}</strong><span>{item.inspection_type} ; {(item.scopes||[]).join(", ")}</span></Link>)}{!historical.length?<p className="ember-page-subtitle">Nog geen historische cases.</p>:null}</div></>:<div className="inspection-empty">Nog geen inspectiecase voor deze installatie.</div>}</section></div>
}
